### ISSUE TITLE
Exception in onDidFinishLoadingStyle Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.location.LocationComponent.setLocationComponentEnabled(boolean)' on a null object reference

### ISSUE THREAD

**Issue by nasmuris** [react-native-mapbox-gl/maps#869]
**Describe the bug**
    private vodid stateChanged() getting called before `mLocationComponent` is initiated on map load hence resulting in `NullPointerException`
```
2020-05-11 13:04:23.746 9008-9008/? E/Mbgl-MapChangeReceiver: Exception in onDidFinishLoadingStyle
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.location.LocationComponent.setLocationComponentEnabled(boolean)' on a null object reference
        at com.mapbox.rctmgl.components.location.LocationComponentManager.stateChanged(LocationComponentManager.java:80)
        at com.mapbox.rctmgl.components.location.LocationComponentManager.showUserLocation(LocationComponentManager.java:55)
        at com.mapbox.rctmgl.components.location.RCTMGLNativeUserLocation.onStyleLoaded(RCTMGLNativeUserLocation.java:55)
        at com.mapbox.mapboxsdk.maps.MapboxMap.getStyle(MapboxMap.java:119)
        at com.mapbox.rctmgl.components.location.RCTMGLNativeUserLocation.onMapReady(RCTMGLNativeUserLocation.java:43)
        at com.mapbox.mapboxsdk.maps.MapView.getMapAsync(MapView.java:1109)
        at com.mapbox.rctmgl.components.location.RCTMGLNativeUserLocation.addToMap(RCTMGLNativeUserLocation.java:30)
        at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.addQueuedFeatures(RCTMGLMapView.java:526)
        at com.mapbox.rctmgl.components.mapview.RCTMGLMapView$1.onStyleLoaded(RCTMGLMapView.java:430)
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:964)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:221)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1316)
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1106)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6923)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
2020-05-11 13:04:23.751 9008-9312/? E/ReactNativeJS: 'Mapbox error', 'Exception in onDidFinishLoadingStyle', { level: 'error',
      tag: 'Mbgl-MapChangeReceiver',
      message: 'Exception in onDidFinishLoadingStyle' }
```

**To Reproduce**

Example:
```js
<MapboxGL.MapView
        ref={map}
        style={[styles.container, props.style]}
        compassEnabled={false}
        onRegionIsChanging={onRegionIsChanging}
        rotateEnabled={props.rotationEnabled && !props.disableInteractions}
        onRegionDidChange={onRegionChanged}
        regionDidChangeDebounceTime={10}
        pitchEnabled={false}
        scrollEnabled={!props.disableInteractions}
        zoomEnabled={!props.disableInteractions}
        onLayout={props.onLayout}
        onPress={onPress}
      >
        <MapboxGL.Camera
          ref={camera}
          maxZoomLevel={18}
          defaultSettings={mapSettings}
          followUserLocation={props.keepUserCentered}
          followUserMode="normal"
        />
        {props.children}
        {/*
        //@ts-ignore*/}
        {props.showUserLocation && <MapboxGL.UserLocation showsUserHeadingIndicator renderMode="native" />}
      </MapboxGL.MapView>
```

**Versions:**
 - Platform: Android
 - Emulator/ Simulator: no
 - OS: Android 8
 - react-native-mapbox-gl 8.1.0-beta
 - React Native Version 61.2

**Additional context**
seems to be fixed by simple early return:
```
private void stateChanged() {
        if (mLocationComponent == null) return;
...
```

**Comment by mfazekas** [comment]
@nasmuris can you make a PR, with the suggested early return?! There are also some other methods that there that might use the same treatment

**Comment by nasmuris** [comment]
@mfazekas Sorry for misleading suggestion, I've discovered I've been updating the locationComponent once again after initial load manually by setting setting followUserLocation to true, hence it worked for me, so we need to find some other way to fix this bug, will try to give it some more time later in upcoming days

**Comment by baijii** [comment]
This is kind of blocking for me as well. The problem does not occur with `renderMode="normal"`

Maybe it's somehing there:
https://github.com/react-native-mapbox-gl/maps/blob/master/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java#L61

```java
    @SuppressLint("MissingPermission")
    @Override
    public void onStyleLoaded(@NonNull Style style) {
        Context context = getContext();
        if (!PermissionsManager.areLocationPermissionsGranted(context)) {
            return;
        }

        LocationComponentManager locationComponent = mMapView.getLocationComponentManager();
        locationComponent.showUserLocation(mEnabled);
    }

    public void setRenderMode(@RenderMode.Mode int renderMode) {
        LocationComponentManager locationComponent = mMapView.getLocationComponentManager();
        locationComponent.setRenderMode(renderMode);
    }
```

I tried copying the PermissionsManager-Lines to the other method to have that early return. But it didn't work. I have no idea what I'm doing, hopefully someone else is smarter than me.

**Comment by nasmuris** [comment]
Just  started to examine the issue and I'm having troubles with the `LocationComponentManager` being updated from both `RCTMGLNativeUserLocation` and `RCTMGLCamera`
from my point of view the userLocation related props (`followUserLocation`, `followUserMode`, `followZoomLevel`, `followPitch`, `followHeading`) should be part of `UserLocation` component, not the `Camera` itself as I can see those components/props interfere with each other

**Comment by baijii** [comment]
@nasmuris This could also be the source of many issues I have. So does the `followPitch` and `followZoomLevel` only sometimes apply (kind of a race condition, I guess). Also observing and setting the trackingMode via `onUserTrackingModeChange` could lead in an infinity loop of resetting the trackingModes.

**Comment by RobertSasak** [comment]
I can confirm that this is still an issue on today's master. As far I can see *mMapView* is null in 
https://github.com/react-native-mapbox-gl/maps/blob/452ce86355a6993e96617cf799b98876668b79e7/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java#L59

I tried to simply add a null check, but that leads to similar issue another place. It seems that the order how *mapView* object is passed by is wrong. Any suggestions how to proceed in funding a bug?

**Comment by kuwatog** [comment]
for me it occurs when adding 
implementation 'com.google.android.gms:play-services-location:17.0.0'

I added this to gradle because of device location being turned ON.

**Comment by lukeramsden** [comment]
I just got this crash too, exact same log.

**Comment by samchan0221** [comment]
> I just got this crash too, exact same log. Could this be re-opened?

I got this crash as well whenever i add an Annotation into a MapView

**Comment by systemlevel** [comment]
This crash does occur for us when rendering native mode on Android.

**Comment by ReidTait** [comment]
I also just had this crash occur with nativeRendering enabled for <MapboxGL.UserLocation/> on Android. Can we re-open this issue?

**Comment by sheten** [comment]
Same issue for me, using this device:
![131932685_187658229693248_8131658291336913323_n](https://user-images.githubusercontent.com/59844932/102597013-a651bc00-4122-11eb-9eff-d3fb765e0803.png)

**Comment by Arkolos** [comment]
I also agree to reopen. I have this issue with version 8.1.0-rc10 .

I get this issue when I have `renderMode="native"` on the `MapboxGL.UserLocation` when the Camera does not have `followUserLocation` prop (if `followUserLocation` is set to true it works)

**Comment by Wandergin** [comment]
Solved by not using renderMode="native" on Android. It works fine on iOS, so it's worth doing a ternary (conditional) distinguishing by Platform.OS so that the correct component is chosen.

**Comment by mzu** [comment]
This is still happening as per original issue description. Tested with 

- Simulator and Android 10
- @react-native-mapbox-gl/maps": "8.1.0" 

`renderMode="native"` on `MapboxGL.UserLocation`

**Comment by mzu** [comment]
> I also agree to reopen. I have this issue with version 8.1.0-rc10 .
> 
> I get this issue when I have `renderMode="native"` on the `<MapboxGL.UserLocation />` when the `<Camera />` does not have `followUserLocation` prop (if `followUserLocation` is set to true it works)

Leaving `followUserLocation={true}` has the side effect of not being able to use `Camera.moveTo(coordinates, duration)` anymore, which I required.

Good new is, it is possible to set `followUserLocation` back to `false` during runtime (I used `MapView.onDidFinishLoadingStyle()` for this). This was safe to do, the error only seemed to happen during initialisation.

@mfazekas Would it be worth reopening this issue?

**Comment by xaiamov** [comment]
I have the same issue on Andorod with `renderMode='native'`.
It should be open unless there is no solution found.

**Comment by savv** [comment]
Also hit this bug :-|. This issue seems to go away with 8.2

**Comment by duyta7598** [comment]
Any update on this? I can't even use MapboxGL.MarkerView

**Comment by realroutein** [comment]
Using different style works for me

`const defaultStyle = {
  version: 8,
  name: 'Land',
  sources: {
    map: {
      type: 'raster',
      tiles: ['https://mt1.google.com/vt/lyrs=r&x={x}&y={y}&z={z}'],
      tileSize: 256,
      minzoom: 1,
      maxzoom: 19,
    },
  },
  layers: [
    {
      id: 'background',
      type: 'background',
      paint: {
        'background-color': '#f2efea',
      },
    },
    {
      id: 'map',
      type: 'raster',
      source: 'map',
      paint: {
        'raster-fade-duration': 100,
      },
    },
  ],
};

<MapboxGL.MapView
   onPress={this.onMapPress}
   zoomLevel={15}				  
   styleJSON={JSON.stringify(defaultStyle)}
  centerCoordinate={[11.256, 43.770]}
  style={{flex:1}}
  ref={ref => this.mapView = ref}>
      <MapboxGL.PointAnnotation draggable coordinate={[11.256, 43.770]} />
      <MapboxGL.Camera ref={ref => this.mapCamera = ref} />
</MapboxGL.MapView>
`

**Comment by RobertSasak** [comment]
@realroutein  Can you please describe what is different about this one?

**Comment by mawrukh** [comment]
> Any update on this? I can't even use MapboxGL.MarkerView

same here, were you able to resolve it?
